title: Meya Midleton's Blog

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Hauntingly Meya 👻]
description: [Unfiltered and unapologetic — just real moments of truth, courage, and vulnerability meant to inspire others to be the same.]
